name: Frontend CI

on:
  workflow_call:
    inputs:
      base-tag:
        required: true
        type: string
      image-name-prefix:
        required: true
        type: string
      image-name-suffix:
        required: true
        type: string
      node-version:
        required: true
        type: string
      volto-version:
        required: true
        type: string
      working-directory:
        required: false
        type: string
        default: frontend

jobs:
  code-analysis:
    name: "Code analysis checks"
    uses: plone/meta/.github/workflows/frontend-code.yml@2.x
    with:
      node-version: ${{ inputs.node-version }}
      working-directory: ${{ inputs.working-directory }}

  unit:
    name: "Run unit tests"
    uses: plone/meta/.github/workflows/frontend-unit.yml@2.x
    with:
      node-version: ${{ inputs.node-version }}
      working-directory: ${{ inputs.working-directory }}

  i18n:
    name: "Run i18n checks"
    uses: plone/meta/.github/workflows/frontend-i18n.yml@2.x

    with:
      node-version: ${{ inputs.node-version }}
      working-directory: ${{ inputs.working-directory }}

  storybook:
    name: "Storybook"
    uses: plone/meta/.github/workflows/frontend-storybook.yml@2.x
    needs:
        - code-analysis
        - unit
        - i18n
    with:
      node-version: ${{ inputs.node-version }}
      working-directory: ${{ inputs.working-directory }}
      deploy: false

  release:
    name: "Frontend: Build and publish container image"
    uses: plone/meta/.github/workflows/container-image-build-push.yml@2.x
    needs:
      - code-analysis
      - i18n
      - unit
      - storybook
    permissions:
      contents: read
      packages: write
    with:
      base-tag: ${{ inputs.base-tag }}
      image-name-prefix: ${{ inputs.image-name-prefix }}
      image-name-suffix: ${{ inputs.image-name-suffix }}
      working-directory: ${{ inputs.working-directory }}
      build-args: |
        VOLTO_VERSION=${{ inputs.volto-version }}
      push: ${{ github.event_name != 'pull_request' }}
    secrets:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}


  report:
    name: "Final report"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - code-analysis
      - unit
      - i18n
      - storybook
      - release
    steps:
      - name: Write report
        run: |
          echo '# Workflow Report' >> $GITHUB_STEP_SUMMARY
          echo '| Job ID | Conclusion |' >> $GITHUB_STEP_SUMMARY
          echo '| --- | --- |' >> $GITHUB_STEP_SUMMARY
          echo '| code-analysis | ${{ needs.code-analysis.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| unit | ${{ needs.unit.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| i18n | ${{ needs.i18n.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| storybook | ${{ needs.storybook.result }} |' >> $GITHUB_STEP_SUMMARY
          echo '| release | ${{ needs.release.result }} |' >> $GITHUB_STEP_SUMMARY
